
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <div className="p-4 bg-yellow-100 border-l-4 border-yellow-500 text-yellow-800 rounded-r-lg">
      <div className="flex items-start">
        <div className="flex-shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
        </div>
        <div className="ml-3">
          <p className="text-sm font-bold">
            Important Legal Notice
          </p>
          <p className="text-sm mt-1">
            The document generated by this tool is for informational purposes only and is not a substitute for professional legal advice. Always consult with a qualified lawyer to review your Terms of Service and ensure it meets the specific legal needs of your business.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
